### PR TITLE
Multiscale calculation for 2D/cylindal coordinate system

### PR DESCRIPTION
**Pull request by uemoto1**
In this pull request, I have added a new modification which mainly 
provides the electromagnetic calculation mode for the cylindal symmetric 
system, e.g. the propagation, absorption of the cylindal vector beams.

- Add new option of FDTDdim: '2DC' (2D cylindal coordinate)
- Fix the problem of electromagnetic gauge conversion in previous version.
- Modify the output format of 'SYSName_Ac_??????.out' file.
  (add the new column to write out the Acx and Ex components ...etc)
- Add new routine to calculate the matter energy by integrating the Joulle heating.
  (also written in the 'SYSName_Ac_??????.out' file) 
- Fix a bug of the output filename caused by the insufficiency of 
  filename variables when the length SYSName/Directory is too long.

### CODE REVIEW

**Comment by shunsuke-sato** [comment]
Thank you for your contribution. I have a question.
What was "the problem of electromagnetic gauge conversion in previous version"?

**Comment by shunsuke-sato** [comment]
I have a couple of comments.
1. Lines from 434 to 446 in ms.f90 write the data of the vector fields and current. I guess that the x components of both quantities should be also written here. Otherwise, we lose the information.

2. I would suggest using double precision for floating numbers explicitly. For examples, 0.25, 0.50 1.00, and 3.8317 should be something like 0.25d0, 0.5d0, 1d0, 3.8317d0. Otherwise, floating numbers will be treated as single precision, which is default.

**Comment by uemoto1** [comment]
Hi, Sato-san!

Thank you for giving me the advices! I tried to fix the points you claimed:
- Add new column to the output file `Ac_M????.out`, `Ac_Vac.out` and `Ac_Vac_back.out` to write the x-component of the "vector potential field" and "macroscopic current density".
- Fix the numerical literals in source code to explicitly indicate the floating point precision.

The current PR is updated to contain the code improvement above.

**Comment by shunsuke-sato** [comment]
Thanks for updating!

**Pull request merged**
