### PR TITLE
Fix the input file format, converter script and examples

### PR DESCRIPTION
**Pull request by uemoto1**
This modification allows `ARTED/dev_salmon` to read the same input file format of present SALMON-TDDFT code. It makes possible to use for the calculation test of SALMON.
- Modify the format of mode switch in `main.f90` such as
```
&group_function
    cfunction='nanostructure|singlecell|multiscale'
    /
```

- Modify the input file converter `/data/arted2salmon.py`
- Convert the input file examples for new file formats `/data/*.nml2`

### CODE REVIEW

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for the implementation.
I tried to test it, but it does not work. On my environment (gfortran), ARTED cannot read "cfunction" from an input. Perhaps, this problem is related to a property of pointer. When I remove `cfunction` and use `calc_mode` directly in `main.f90`, it works.

Have you check if the program run properly on your environment? If so, the problem depends on environment.

**Comment by uemoto1** [comment]
Thank you, Sato-san.
Now I have retry to test the current code in intel fortran, and it seems like working.
I will test this by other compiler...

**Comment by uemoto1** [comment]
Okey, I succeed to reproduce your report. This is very weird behavior, and the point what we have to be careful in the gfortran environment...

**Comment by shunsuke-sato** [comment]
@uemoto1 san, thank you for your quick test!
Now I also tried the intel compiler, and it seems to work well too.
I think the code should also work with the GNU compiler. Thus, we should solve this problem.

By the way, why did you introduce `cfunction` as a pointer for `calc_mode`. I personally think that the direct use of `calc_mode` is simpler and more meaningful for both users and developers.

**Comment by shunsuke-sato** [comment]
@uemoto1 san, I did not see your latest commit which solves the problem of gfortran, but now I found it. I'm sorry about that. I'll merge it.

Probably, the input parameter of `cfunction` is related to SALMON, and thus, it would be discussed in the next SALMON meeting. Just let me write what I think:
A keyword of `cfunction` is too general for input since it is difficult to understand the rope of this parameter by the name. Therefore, this name would be user-unfriendly. Furthermore, `cfunction` is internally transferred to `calc_mode`. If we directly load this control variable as `calc_mode`, we can avoid the internal variable transfer and keep the code simple!

**Pull request merged**
